### ISSUE TITLE
PEOPLE: Rollenberechtigungen ändern

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pro_natura#10]
Die Berechtigungen bei Pro Natura spiegeln nicht mehr die tatsächliche Verwendung gewisser Rollen wieder, weshalb einzelne Berechtigungsanpassungen vorgenommen werden sollen.

Konkret soll die Rolle "PL Jugend" auf dem Dachverband neu auch Rechte für die Impersonierung anderer Personen erhalten.
Die Rolle "Mitglied" in Gremien keine Rechte mehr haben -> group_and_below_read entfernen

# Mockup
![grafik](https://github.com/hitobito/hitobito_pro_natura/assets/100761305/6fb82d0b-b81b-4242-b09f-45955e647184)

# Tech-Spec

- Rolle PL Jugend auf Dachverband `:impersonation` ergänzen
- Rolle Mitglied auf Gremium `:group_and_below_read` entfernen

# ToDo

- [x] Rolle Dachverband/PL Jugend anpassen
- [x] Rolle Gremium/Mitglied anpassen
- [x] Specs anpassen oder hinzufügen
- [x] Rollenübersicht im README aktualisieren
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [x] Release-Zeitpunkt klären -> 2.2.0
