### ISSUE TITLE
PEOPLE: Export von Mutationen von Leitungspersonen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_pro_natura#15]
## User Story
Als Person, die bei Pro-Natura die Leitenden administriert möchte ich einen einfachen Weg haben, sämtliche Mutationen aller Personen mit einer Leitendenrolle der vergangengen x Monate einsehen zu können, um Änderungen an,  ehemalige und neue Leitungspersonen einfach zu finden und ins CRM zu überführen.

## Ausgangslage
Dafür gibt es im Pro-Natura Wagon bereits ein Feature.

Auf der Hauptebene kann via das Tab "Mutationen" ein CVS heruntergeladen werden, welches sämtliche Änderungen seit Datum x auflistet:
![grafik](https://github.com/user-attachments/assets/ca8dfae7-57c1-4799-8a3e-8f8b630186c0)

Dabei wird von jeder Person jedoch nur die letzte Änderung ausgegeben. Ändert jemand seine Adresse und bekommt später noch eine neue Rolle, ist nur die Rollenänderung im Export ersichtlich.

Rollenänderungen werden zudem nur aufgelistet, wenn die Hauptgruppe geändert wurde, und im Export ist nur die Rolle ersichtlich, welche als Hauptgruppe gelistet ist.

## Zielzustand
- Neu sollen in dem Export alle Änderungen seit dem angegebenen Datum ersichtlich sein, nicht nur die letzte pro Person. Es soll neu also pro Person nicht mehr nur eine Zeile, sondern mehrere Zeilen möglich sein.
- Neu sollen in dem Export alle Personen vorhanden sein welche eine aktive Rolle Leiter/in in irgendeiner Gruppe haben oder hatten, unabhängig von der Hauptgruppe. Alle Personen welche nirgends eine aktive Rolle Leiter/in haben, müssen nicht berücksichtigt werden und sollen im Export nicht enthalten sein.
- Es müssen alle Änderungen von Personen vorhanden sein welche im ausgewerteten Zeitpunkt eine Leiter/in Rolle haben, oder hatten. Verliert jemand die Rolle muss dies im Export ersichtlich sein. Wird eine Person gelöscht welche die Rolle hatte, muss die im Export noch ersichtlich sein. Entscheidend ist die Rolle zum Mutationszeitpunkt nicht zum Exportzeitpunkt.
- Der Export soll neu auch das Geburtsdatum von Personen beinhalten. (Sonnst gleiche Attribute wie bis anhin.)

# Tech-Spec

- vollständige Übersicht über Mutationen
- Personen können mehrfach auftreten
- Alle Personen, die im Zeitraum Leitungsrollen haben, sollen betrachten werden

# ToDo

- [x] Domainklasse `Person::Mutations::Fetcher` anpassen
    - `Person::Mutations::Fetcher` sammelt die Personen, die gelistet werden sollen
        - es kann sinnvoll sein, ein Person mehrfach aufzulisten
    - `Person::Mutations::Mutation` ist eine Änderungszeile
        - `#fetch_last_role` ist vermutlich für die Änderung hier relevant
        - weitere ähnliche Fällen müssen getestet werden.
    - `Export::Tabular::People::Mutations` rendert pro Mutation eine Zeile
- [x] Specs schreiben
- [ ] Feature gemäss manuellem Testing fixen und neuen PR erstellen (vormaliger Zustand musste wegen dem Merge Freeze in #21 revertet werden) 
- [ ] Die 3 pending Tests in [fetcher_spec.rb](https://github.com/hitobito/hitobito_pro_natura/blob/master/spec/domain/person/mutations/fetcher_spec.rb) reaktivieren und fixen
- [ ] Kunde wegen Testen auf Integration informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by njaeggi** [comment]
Beim Testen sind mit folgende Punkte zu diesem Feature aufgefallen:
- Es werden nicht nur Leiter/in Rollen beachtet sondern alle Rollen ausser Passivrollen
- Es werden auch andere Gruppen als die Hauptebene beachtet
